version: '3.4'

services:
  testnt.main.api.rest:
    container_name: Testnt.Main.Api.Rest
    image: ${DOCKER_REGISTRY-}testntmainapirest
    build:
      context: .
      dockerfile: src/Testnt.Main.Api.Rest/Dockerfile
      args:
        - skip_client_build=true

  testnt.identityserver:
    container_name: Testnt.IdentityServer
    image: ${DOCKER_REGISTRY-}testntidentityserver
    build:
      context: .
      dockerfile: src/Testnt.IdentityServer/Dockerfile

 

  postgres:
    image: postgres
    container_name: 'postgres'
    