version: '3.4'

services:
  testnt.main.api.rest:
    image: ${DOCKER_REGISTRY-}testntmainapirest
    build:
      context: .
      dockerfile: src/Testnt.Main.Api.Rest/Dockerfile
      args:
        - skip_client_build=true

  testnt.identityserver:
    image: ${DOCKER_REGISTRY-}testntidentityserver
    build:
      context: .
      dockerfile: src/Testnt.IdentityServer/Dockerfile

  testnt.angular.app:
    image: ${DOCKER_REGISTRY-}testntangularapp
    container_name: 'testnt.angular.app'
    build:
      context: .
      dockerfile: src/Testnt.Main.Api.Rest/ClientApp/Dockerfile
    ports:
      - "4200:4200" 
      - "49153:49153"
    volumes:
      - ./src/Testnt.Main.Api.Rest/ClientApp:/app

  postgres:
    image: postgres
    container_name: 'postgres'
    