version: '3.4'

services:
  testnt.main.api.rest:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__PostgresTestntMainConnectionString=Host=postgres;Database=Testnt;Username=postgres;Password=postgres
      - IdentityServer__Url=http://localhost:5000
    ports:
      - "7000:80"
      - "7001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  testnt.identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=TestntIdentity;Username=postgres;Password=postgres
      - Client__Ip__0=http://localhost:7000
    ports:
      - "5000:80"
      - "5001:443"

  postgres:
    ports:
      - "5432:5432" 
    environment:
      - "POSTGRES_PASSWORD=postgres"